
# 1. RDS Secret
apiVersion: v1
kind: Secret
metadata:
  name: microservices-db-credentials
type: Opaque
stringData:
  DB_HOST: banking-db-primary.c1o0amwco2yd.us-west-2.rds.amazonaws.com
  DB_PORT: "5432"
  DB_NAME: bankingdb
  DB_USER: postgres
  DB_PASSWORD: ${{ secretes.DB_PASSWORD}}
  DB_SSLMODE: "verify-full"
  DB_SSLROOTCERT: "/certs/global-bundle.pem"


# ConfigMap for RDS SSL certificate

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rds-cert-config
data:
  global-bundle.pem: |
    -----BEGIN CERTIFICATE-----
    ...paste your RDS CA cert here...
    -----END CERTIFICATE-----


# Deployments

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: 986778210363.dkr.ecr.us-west-2.amazonaws.com/accounts:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: microservices-db-credentials
          volumeMounts:
            - name: rds-cert
              mountPath: /certs
      volumes:
        - name: rds-cert
          configMap:
            name: rds-cert-config
            items:
              - key: global-bundle.pem
                path: global-bundle.pem

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: 986778210363.dkr.ecr.us-west-2.amazonaws.com/accounts:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: microservices-db-credentials
          volumeMounts:
            - name: rds-cert
              mountPath: /certs
      volumes:
        - name: rds-cert
          configMap:
            name: rds-cert-config
            items:
              - key: global-bundle.pem
                path: global-bundle.pem

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: 986778210363.dkr.ecr.us-west-2.amazonaws.com/accounts:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: microservices-db-credentials
          volumeMounts:
            - name: rds-cert
              mountPath: /certs
      volumes:
        - name: rds-cert
          configMap:
            name: rds-cert-config
            items:
              - key: global-bundle.pem
                path: global-bundle.pem

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transactions
  template:
    metadata:
      labels:
        app: transactions
    spec:
      containers:
        - name: transactions
          image: 986778210363.dkr.ecr.us-west-2.amazonaws.com/accounts:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: microservices-db-credentials
          volumeMounts:
            - name: rds-cert
              mountPath: /certs
      volumes:
        - name: rds-cert
          configMap:
            name: rds-cert-config
            items:
              - key: global-bundle.pem
                path: global-bundle.pem


# Services

---
apiVersion: v1
kind: Service
metadata:
  name: accounts-service
spec:
  selector:
    app: accounts
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: transactions-service
spec:
  selector:
    app: transactions
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
