##############################
# Transactions Service
##############################
apiVersion: v1
kind: Service
metadata:
  name: transactions-service
spec:
  selector:
    app: transactions
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
